//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "motorSetup.h"
#include "functionsLibrary.h"
task main(){
	motor[motorG] = 20;
	motor[motorF] = 20;
	sleep(450);
	stopMotors(1);
	straight(2.5, 100);
	goRight(75);
	straight(2, 100);
	Sandstorm();
}
